#!/bin/zsh
...toggle_zsh_init_echos() {(
    set -xe
    [ -d ~/.zsh ]
    subdirs=(.zsh/env .zsh/profile .sh .zsh/rc .zsh/login)
    if [ -e ~/.zsh/env/_echo ]; then
        for n in $subdirs; do
            rm ~/$n/_echo || true
        done
    else
        for n in $subdirs; do
            echo 'echo "+ In $0"' >| ~/$n/_echo
        done
    fi
)}
